# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: rogovski.log
info_title: rogovski.info
email: michaeljrogowski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the human equivalent of a log file; it records events and statuses
  that I find interesting and relevent. My contact information can be found
  to the left.
<<<<<<< HEAD
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rogovski.github.io" # the base hostname & protocol for your site
twitter_username: kungsolo
github_username:  rogovski

# Build settings
markdown: kramdown
