# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               ROGOVSKI
tagline:             '.log'
description:         'the sweetest of slogans'
url:                 http://rogovski.github.io/
baseurl:             ''
paginate:            5

markdown:            redcarpet

redcarpet:
  extensions:        ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter:         pygments

# About/contact
author:
  name:              Michael Rogowski
  url:               http://rogovski.github.io/
  email:             michaeljrogowski@gmail.com

# github info
github:
  repo:              https://github.com/rogovski/rogovski.github.io

# Custom vars
version:             1.0.0
